### ISSUE TITLE
Release v1.0 On CPAN

### ISSUE THREAD

**Issue by wbraswell** [denny/ShinyCMS#46]
Now we have an official goal!

**Comment by denny** [comment]
I've just bumped the version number to 0.9.0 - this marks the beginning of a serious effort to get us to 1.0 this year.  Fingers crossed!

**Comment by wbraswell** [comment]
Nice!!
ALL FINGERS CROSSED!!!

**Comment by wbraswell** [comment]
@denny 
Is there some specific reason you do not want to release onto CPAN?

**Comment by denny** [comment]
No objection, although I think CPAN is designed for libraries rather than applications.  I know it's possible to bundle apps up for it, but it's always felt a bit kludgy to me.  I'd be more interested in getting the Docker image working properly (currently it doesn't seem to work well with multiple installs on a shared server, it gets very resource hungry) and/or creating some sort of 'install wizard' script so that people could install and configure by pasting a one liner into a terminal - something like 'curl -sf https://shinycms.org/install/install.sh | sh' that will install Catalyst etc from CPAN if needed, ask where to put the CMS support files, and then ask questions to populate an initial shinycms.conf for them.

All that said, I closed this because I skipped 1.0 slightly when I switched to the Ubuntu-style versioning.  :)
